version: "3.9"

services:
  omnichannel-frontend:
    build: .
    image: angular
    ports:
      - "4200:4200"
    depends_on:
      - omnichannel-backend

  omnichannel-backend:
    build: .
    image: nestjs
    ports:
      - "3000:3000"
